service: 1988
app: 1988

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  stackName: best-of-1988

# you can overwrite defaults here
region: us-east-1

functions:
  best:
    handler: handlers/handler.best
    events:
      - http:
          path: best
          method: get

