service: Google # the word "google" can't be in here

provider:
  name: google
  stage: dev
  runtime: nodejs8
  region: us-central1
  project:  best-of-1988 # your project on google - create this first
  #
  #
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/best-of-1988.json

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  best:
    handler: best
    events:
      - http: best
